package com.android.monitoring.constant;

import lombok.Getter;

@Getter
public enum WebSocketMessageHeader {
    // connection
    REQUEST_MY_CONNECTION_ID_ON_SERVER("REQUEST_MY_CONNECTION_ID_ON_SERVER"),

    // admin
    ADMIN_REQUEST_MONITORING("ADMIN_REQUEST_MONITORING"),

    // device information
    ADMIN_REQUEST_CLIENT_LOCATION("ADMIN_REQUEST_CLIENT_LOCATION"),
    ADMIN_REQUEST_CLIENT_DEVICE_INFO("ADMIN_REQUEST_CLIENT_DEVICE_INFO"),

    CLIENT_DEVICE_LOCATION_RESPONSE("CLIENT_DEVICE_LOCATION_RESPONSE"),
    CLIENT_DEVICE_INFO_RESPONSE("CLIENT_DEVICE_INFO_RESPONSE"),

    // device control
    ADMIN_REQUEST_CLIENT_DEVICE_REBOOT("ADMIN_REQUEST_CLIENT_DEVICE_REBOOT"),
    ADMIN_REQUEST_CLIENT_DEVICE_DISABLE_STATUS_BAR("ADMIN_REQUEST_CLIENT_DEVICE_DISABLE_STATUS_BAR"),
    ADMIN_REQUEST_CLIENT_DEVICE_LOCK_SCREEN("ADMIN_REQUEST_CLIENT_DEVICE_LOCK_SCREEN"),

    // logging
    ADMIN_REQUEST_CLIENT_DEVICE_START_REAL_TIME_LOGS("ADMIN_REQUEST_CLIENT_DEVICE_START_REAL_TIME_LOGS"),
    ADMIN_REQUEST_CLIENT_DEVICE_END_REAL_TIME_LOGS("ADMIN_REQUEST_CLIENT_DEVICE_END_REAL_TIME_LOGS"),
    CLIENT_DEVICE_LOG_RESPONSE("CLIENT_DEVICE_LOG_RESPONSE"),

    // web rtc screen sharing
    WEBRTC_SIGN_ON("WEBRTC_SIGN_ON"),
    WEBRTC_START_STREAMING("WEBRTC_START_STREAMING"),
    WEBRTC_END_STREAMING("WEBRTC_END_STREAMING"),

    ADMIN_REQUEST_WEBRTC_START_STREAMING("ADMIN_REQUEST_WEBRTC_START_STREAMING"),

    WEBRTC_OFFER("WEBRTC_OFFER"),
    WEBRTC_ANSWER("WEBRTC_ANSWER"),
    WEBRTC_ICE_CANDIDATE("WEBRTC_ICE_CANDIDATE"),

    // todo
    SCREEN_MIRRORING("SCREEN_MIRRORING"),
    REMOTE_UPDATE("REMOTE_UPDATE"),
    REMOTE_SHELL("REMOTE_SHELL");

    WebSocketMessageHeader(String stringValue) {
        this.stringValue = stringValue;
    }

    private final String stringValue;
}